<?php
/**
 * Plugin Name: NU Multisite Global Settings
 * Description: Settings to apply to all network sites
 * Version: 1.0.0
 * Author: Dan Scott
 *
 * @package national-university
 *
 * Contains data, shortcodes, and scripts that are used across all network sites
 *   - Global Variables: Allows for input of global variables (alumni numbers, phone number, etc) that should remain constant across all network sites
 *   - Related Shortcodes: Creates shortcodes for outputting the above-reference global variables across all network sites
 *   - Web Services: Creates a centralized config page for various web services (GTM, optimizely, etc) that are used across various network sites
 *
 * @todo Global: Better error checking & handling. Basic field validation for phone numbers, urls, etc?
 * @todo Global: Might simplify a lot of code to just add sub-pages under existing "settings" menu, rather than building out a whole new menu option. Maybe? Look into a bit more
 * @todo Global - create parent-level "create_slug()" function? Lots of slugs (for pretty much anything being saved in the DB) are bering manually created in lots of different places
 * @todo Web Services: Optimizely - "Target IDs" field needs to support multiple comma-delimited IDs
 * @todo Shortcodes - Keep working on functionality/documentation page
 */

namespace NUEDU_Network;

if ( ! defined( 'WPINC' ) ) {
	die( 'YOU SHALL! NOT! PASS!' );
}

define( 'NUEDU_NETWORK_FUNC_PATH', plugin_dir_path( __FILE__ ) );
define( 'NUEDU_NETWORK_FUNC_URL', plugin_dir_url( __FILE__ ) );

// Require our config file. Contains an object with static properties, containing arrays used for variables & web services.
// In theory, any future updates/additions/etc to global variables can be made in this file.
require_once NUEDU_NETWORK_FUNC_PATH . 'class-config.php';

// Activation hook. Currently only used to ensure that plugin is only activated at network-level, and not site-level.
// $network_wide is generated by WP for plugin activation functions, boolean true/false.
register_activation_hook( __FILE__, function( $network_wide ) {
	require_once NUEDU_NETWORK_FUNC_PATH . 'autoload/class-activation.php';
	new Autoload\Activation( $network_wide );
} );


// Initialize plugin & load files.
use NUEDU_Network\Autoload\Init;

add_action( 'plugins_loaded', function() {
	require_once NUEDU_NETWORK_FUNC_PATH . 'autoload/autoloader.php'; // phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingCustomConstant

	// Initializing file is in autoload/class-init.php. Refer to file for setup.
	new Init();
} );